# encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Cidades do Paraná
e = Estado.create(:sigla => 'PR', :nome => "Paraná")
e.cidades.create(:nome => "Abatiá")
e.cidades.create(:nome => "Adrianópolis")
e.cidades.create(:nome => "Agudos do Sul")
e.cidades.create(:nome => "Almirante Tamandaré")
e.cidades.create(:nome => "Altamira do Paraná")
e.cidades.create(:nome => "Alto Paraná")
e.cidades.create(:nome => "Alto Paraíso")
e.cidades.create(:nome => "Alto Piquiri")
e.cidades.create(:nome => "Altônia")
e.cidades.create(:nome => "Alvorada do Sul")
e.cidades.create(:nome => "Amaporã")
e.cidades.create(:nome => "Ampére")
e.cidades.create(:nome => "Anahy")
e.cidades.create(:nome => "Andirá")
e.cidades.create(:nome => "Ângulo")
e.cidades.create(:nome => "Antonina")
e.cidades.create(:nome => "Antônio Olinto")
e.cidades.create(:nome => "Apucarana")
e.cidades.create(:nome => "Arapongas")
e.cidades.create(:nome => "Arapoti")
e.cidades.create(:nome => "Arapuã")
e.cidades.create(:nome => "Araruna")
e.cidades.create(:nome => "Araucária")
e.cidades.create(:nome => "Ariranha do Ivaí")
e.cidades.create(:nome => "Assaí")
e.cidades.create(:nome => "Assis Chateaubriand")
e.cidades.create(:nome => "Astorga")
e.cidades.create(:nome => "Atalaia")
e.cidades.create(:nome => "Balsa Nova")
e.cidades.create(:nome => "Bandeirantes")
e.cidades.create(:nome => "Barbosa Ferraz")
e.cidades.create(:nome => "Barra do Jacaré")
e.cidades.create(:nome => "Barracão")
e.cidades.create(:nome => "Bela Vista da Caroba")
e.cidades.create(:nome => "Bela Vista do Paraíso")
e.cidades.create(:nome => "Bituruna")
e.cidades.create(:nome => "Boa Esperança")
e.cidades.create(:nome => "Boa Esperança do Iguaçu")
e.cidades.create(:nome => "Boa Ventura de São Roque")
e.cidades.create(:nome => "Boa Vista da Aparecida")
e.cidades.create(:nome => "Bocaiúva do Sul")
e.cidades.create(:nome => "Bom Jesus do Sul")
e.cidades.create(:nome => "Bom Sucesso")
e.cidades.create(:nome => "Bom Sucesso do Sul")
e.cidades.create(:nome => "Borrazópolis")
e.cidades.create(:nome => "Braganey")
e.cidades.create(:nome => "Brasilândia do Sul")
e.cidades.create(:nome => "Cafeara")
e.cidades.create(:nome => "Cafelândia")
e.cidades.create(:nome => "Cafezal do Sul")
e.cidades.create(:nome => "Califórnia")
e.cidades.create(:nome => "Cambará")
e.cidades.create(:nome => "Cambira")
e.cidades.create(:nome => "Cambé")
e.cidades.create(:nome => "Campina Grande do Sul")
e.cidades.create(:nome => "Campina da Lagoa")
e.cidades.create(:nome => "Campina do Simão")
e.cidades.create(:nome => "Campo Bonito")
e.cidades.create(:nome => "Campo Largo")
e.cidades.create(:nome => "Campo Magro")
e.cidades.create(:nome => "Campo Mourão")
e.cidades.create(:nome => "Campo do Tenente")
e.cidades.create(:nome => "Candói")
e.cidades.create(:nome => "Cantagalo")
e.cidades.create(:nome => "Capanema")
e.cidades.create(:nome => "Capitão Leônidas Marques")
e.cidades.create(:nome => "Carambeí")
e.cidades.create(:nome => "Carlópolis")
e.cidades.create(:nome => "Cascavel")
e.cidades.create(:nome => "Castro")
e.cidades.create(:nome => "Catanduvas")
e.cidades.create(:nome => "Centenário do Sul")
e.cidades.create(:nome => "Cerro Azul")
e.cidades.create(:nome => "Chopinzinho")
e.cidades.create(:nome => "Cianorte")
e.cidades.create(:nome => "Cidade Gaúcha")
e.cidades.create(:nome => "Clevelândia")
e.cidades.create(:nome => "Colombo")
e.cidades.create(:nome => "Colorado")
e.cidades.create(:nome => "Congonhinhas")
e.cidades.create(:nome => "Conselheiro Mairinck")
e.cidades.create(:nome => "Conta")
e.cidades.create(:nome => "Corbélia")
e.cidades.create(:nome => "Cornélio Procópio")
e.cidades.create(:nome => "Coronel Domingos Soares")
e.cidades.create(:nome => "Coronel Vivida")
e.cidades.create(:nome => "Corumbataí do Sul")
e.cidades.create(:nome => "Cruz Machado")
e.cidades.create(:nome => "Cruzeiro do Iguaçu")
e.cidades.create(:nome => "Cruzeiro do Oeste")
e.cidades.create(:nome => "Cruzeiro do Sul")
e.cidades.create(:nome => "Cruzmaltina")
e.cidades.create(:nome => "Curitiba")
e.cidades.create(:nome => "Curiúva")
e.cidades.create(:nome => "Cândido de Abreu")
e.cidades.create(:nome => "Céu Azul")
e.cidades.create(:nome => "Diamante D'Oeste")
e.cidades.create(:nome => "Diamante do Norte")
e.cidades.create(:nome => "Diamante do Sul")
e.cidades.create(:nome => "Dois Vizinhos")
e.cidades.create(:nome => "Douradina")
e.cidades.create(:nome => "Doutor Camargo")
e.cidades.create(:nome => "Doutor Ulysses")
e.cidades.create(:nome => "Engenheiro Beltrão")
e.cidades.create(:nome => "Entre Rios do Oeste")
e.cidades.create(:nome => "Enéas Marques")
e.cidades.create(:nome => "Esperança Nova")
e.cidades.create(:nome => "Espigão Alto do Iguaçu")
e.cidades.create(:nome => "Farol")
e.cidades.create(:nome => "Faxinal")
e.cidades.create(:nome => "Faza Rio Grande")
e.cidades.create(:nome => "Fernandes Pinheiro")
e.cidades.create(:nome => "Figueira")
e.cidades.create(:nome => "Flor da Serra do Sul")
e.cidades.create(:nome => "Floraí")
e.cidades.create(:nome => "Floresta")
e.cidades.create(:nome => "Florestópolis")
e.cidades.create(:nome => "Flórida")
e.cidades.create(:nome => "Formosa do Oeste")
e.cidades.create(:nome => "Foz do Iguaçu")
e.cidades.create(:nome => "Foz do Jordão")
e.cidades.create(:nome => "Francisco Alves")
e.cidades.create(:nome => "Francisco Beltrão")
e.cidades.create(:nome => "Fênix")
e.cidades.create(:nome => "General Carneiro")
e.cidades.create(:nome => "Godoy Moreira")
e.cidades.create(:nome => "Goioerê")
e.cidades.create(:nome => "Goioxim")
e.cidades.create(:nome => "Grandes Rios")
e.cidades.create(:nome => "Guairaçá")
e.cidades.create(:nome => "Guamiranga")
e.cidades.create(:nome => "Guapirama")
e.cidades.create(:nome => "Guaporema")
e.cidades.create(:nome => "Guaraci")
e.cidades.create(:nome => "Guaraniaçu")
e.cidades.create(:nome => "Guarapuava")
e.cidades.create(:nome => "Guaraqueçaba")
e.cidades.create(:nome => "Guaratuba")
e.cidades.create(:nome => "Guaíra")
e.cidades.create(:nome => "Honório Serpa")
e.cidades.create(:nome => "Ibaiti")
e.cidades.create(:nome => "Ibema")
e.cidades.create(:nome => "Ibiporã")
e.cidades.create(:nome => "Icaraíma")
e.cidades.create(:nome => "Iguaraçu")
e.cidades.create(:nome => "Iguatu")
e.cidades.create(:nome => "Imbaú")
e.cidades.create(:nome => "Imbituva")
e.cidades.create(:nome => "Inajá")
e.cidades.create(:nome => "Indianópolis")
e.cidades.create(:nome => "Inácio Martins")
e.cidades.create(:nome => "Ipiranga")
e.cidades.create(:nome => "Iporã")
e.cidades.create(:nome => "Iracema do Oeste")
e.cidades.create(:nome => "Irati")
e.cidades.create(:nome => "Iretama")
e.cidades.create(:nome => "Itaguajé")
e.cidades.create(:nome => "Itaipulândia")
e.cidades.create(:nome => "Itambaracá")
e.cidades.create(:nome => "Itambé")
e.cidades.create(:nome => "Itapejara d'Oeste")
e.cidades.create(:nome => "Itaperuçu")
e.cidades.create(:nome => "Itaúna do Sul")
e.cidades.create(:nome => "Ivaiporã")
e.cidades.create(:nome => "Ivatuba")
e.cidades.create(:nome => "Ivaté")
e.cidades.create(:nome => "Ivaí")
e.cidades.create(:nome => "Jaboti")
e.cidades.create(:nome => "Jacarezinho")
e.cidades.create(:nome => "Jaguapitã")
e.cidades.create(:nome => "Jaguariaíva")
e.cidades.create(:nome => "Jandaia do Sul")
e.cidades.create(:nome => "Janiópolis")
e.cidades.create(:nome => "Japira")
e.cidades.create(:nome => "Japurá")
e.cidades.create(:nome => "Jardim Alegre")
e.cidades.create(:nome => "Jardim Olinda")
e.cidades.create(:nome => "Jataizinho")
e.cidades.create(:nome => "Jesuítas")
e.cidades.create(:nome => "Joaquim Távora")
e.cidades.create(:nome => "Jundiaí do Sul")
e.cidades.create(:nome => "Juranda")
e.cidades.create(:nome => "Jussara")
e.cidades.create(:nome => "Kaloré")
e.cidades.create(:nome => "Lapa")
e.cidades.create(:nome => "Laranjal")
e.cidades.create(:nome => "Laranjeiras do Sul")
e.cidades.create(:nome => "Leópolis")
e.cidades.create(:nome => "Lidianópolis")
e.cidades.create(:nome => "Lindoeste")
e.cidades.create(:nome => "Loanda")
e.cidades.create(:nome => "Lobato")
e.cidades.create(:nome => "Londrina")
e.cidades.create(:nome => "Luiziana")
e.cidades.create(:nome => "Lunardelli")
e.cidades.create(:nome => "Lupionópolis")
e.cidades.create(:nome => "Mallet")
e.cidades.create(:nome => "Mamborê")
e.cidades.create(:nome => "Mandaguari")
e.cidades.create(:nome => "Mandaguaçu")
e.cidades.create(:nome => "Mandirituba")
e.cidades.create(:nome => "Manfrinópolis")
e.cidades.create(:nome => "Mangueirinha")
e.cidades.create(:nome => "Manoel Ribas")
e.cidades.create(:nome => "Marechal Cândido Rondon")
e.cidades.create(:nome => "Maria Helena")
e.cidades.create(:nome => "Marialva")
e.cidades.create(:nome => "Marilena")
e.cidades.create(:nome => "Mariluz")
e.cidades.create(:nome => "Marilândia do Sul")
e.cidades.create(:nome => "Maringá")
e.cidades.create(:nome => "Maripá")
e.cidades.create(:nome => "Mariópolis")
e.cidades.create(:nome => "Marmeleiro")
e.cidades.create(:nome => "Marquinho")
e.cidades.create(:nome => "Marumbi")
e.cidades.create(:nome => "Matelândia")
e.cidades.create(:nome => "Matinhos")
e.cidades.create(:nome => "Mato Rico")
e.cidades.create(:nome => "Mauá da Serra")
e.cidades.create(:nome => "Medianeira")
e.cidades.create(:nome => "Mercedes")
e.cidades.create(:nome => "Mirador")
e.cidades.create(:nome => "Miraselva")
e.cidades.create(:nome => "Missal")
e.cidades.create(:nome => "Moreira Sales")
e.cidades.create(:nome => "Morretes")
e.cidades.create(:nome => "Munhoz de Melo")
e.cidades.create(:nome => "Nossa Senhora das Graças")
e.cidades.create(:nome => "Nova Aliança do Ivaí")
e.cidades.create(:nome => "Nova América da Colina")
e.cidades.create(:nome => "Nova Aurora")
e.cidades.create(:nome => "Nova Cantu")
e.cidades.create(:nome => "Nova Esperança")
e.cidades.create(:nome => "Nova Esperança do Sudoeste")
e.cidades.create(:nome => "Nova Fátima")
e.cidades.create(:nome => "Nova Laranjeiras")
e.cidades.create(:nome => "Nova Londrina")
e.cidades.create(:nome => "Nova Olímpia")
e.cidades.create(:nome => "Nova Prata do Iguaçu")
e.cidades.create(:nome => "Nova Santa Bárbara")
e.cidades.create(:nome => "Nova Santa Rosa")
e.cidades.create(:nome => "Nova Tebas")
e.cidades.create(:nome => "Novo Itacolomi")
e.cidades.create(:nome => "Ortigueira")
e.cidades.create(:nome => "Ourizona")
e.cidades.create(:nome => "Ouro Verde do Oeste")
e.cidades.create(:nome => "Paiçandu")
e.cidades.create(:nome => "Palmas")
e.cidades.create(:nome => "Palmeira")
e.cidades.create(:nome => "Palmital")
e.cidades.create(:nome => "Palotina")
e.cidades.create(:nome => "Paranacity")
e.cidades.create(:nome => "Paranaguá")
e.cidades.create(:nome => "Paranapoema")
e.cidades.create(:nome => "Paranavaí")
e.cidades.create(:nome => "Paraíso do Norte")
e.cidades.create(:nome => "Pato Bragado")
e.cidades.create(:nome => "Pato Branco")
e.cidades.create(:nome => "Paula Freitas")
e.cidades.create(:nome => "Paulo Frontin")
e.cidades.create(:nome => "Peabiru")
e.cidades.create(:nome => "Perobal")
e.cidades.create(:nome => "Pinhais")
e.cidades.create(:nome => "Pinhal de São Bento")
e.cidades.create(:nome => "Pinhalão")
e.cidades.create(:nome => "Pinhão")
e.cidades.create(:nome => "Piraquara")
e.cidades.create(:nome => "Piraí do Sul")
e.cidades.create(:nome => "Pitanga")
e.cidades.create(:nome => "Pitangueiras")
e.cidades.create(:nome => "Piên")
e.cidades.create(:nome => "Planaltina do Paraná")
e.cidades.create(:nome => "Planalto")
e.cidades.create(:nome => "Ponta Grossa")
e.cidades.create(:nome => "Pontal do Paraná")
e.cidades.create(:nome => "Porecatu")
e.cidades.create(:nome => "Porto Amazonas")
e.cidades.create(:nome => "Porto Barreiro")
e.cidades.create(:nome => "Porto Rico")
e.cidades.create(:nome => "Porto Vitória")
e.cidades.create(:nome => "Prado Ferreira")
e.cidades.create(:nome => "Pranchita")
e.cidades.create(:nome => "Presidente Castelo Branco")
e.cidades.create(:nome => "Primeiro de Maio")
e.cidades.create(:nome => "Prudentópolis")
e.cidades.create(:nome => "Pérola")
e.cidades.create(:nome => "Pérola d'Oeste")
e.cidades.create(:nome => "Quarto Centenário")
e.cidades.create(:nome => "Quatiguá")
e.cidades.create(:nome => "Quatro Barras")
e.cidades.create(:nome => "Quatro Pontes")
e.cidades.create(:nome => "Quedas do Iguaçu")
e.cidades.create(:nome => "Querência do Norte")
e.cidades.create(:nome => "Quinta do Sol")
e.cidades.create(:nome => "Quitandinha")
e.cidades.create(:nome => "Ramilândia")
e.cidades.create(:nome => "Rancho Alegre")
e.cidades.create(:nome => "Rancho Alegre D'Oeste")
e.cidades.create(:nome => "Realeza")
e.cidades.create(:nome => "Rebouças")
e.cidades.create(:nome => "Renascença")
e.cidades.create(:nome => "Reserva")
e.cidades.create(:nome => "Reserva do Iguaçu")
e.cidades.create(:nome => "Ribeirão Claro")
e.cidades.create(:nome => "Ribeirão do Pinhal")
e.cidades.create(:nome => "Rio Azul")
e.cidades.create(:nome => "Rio Bom")
e.cidades.create(:nome => "Rio Bonito do Iguaçu")
e.cidades.create(:nome => "Rio Branco do Ivaí")
e.cidades.create(:nome => "Rio Branco do Sul")
e.cidades.create(:nome => "Rio Negro")
e.cidades.create(:nome => "Rolândia")
e.cidades.create(:nome => "Roncador")
e.cidades.create(:nome => "Rondon")
e.cidades.create(:nome => "Rosário do Ivaí")
e.cidades.create(:nome => "Sabáudia")
e.cidades.create(:nome => "Salgado Filho")
e.cidades.create(:nome => "Salto do Itararé")
e.cidades.create(:nome => "Salto do Lontra")
e.cidades.create(:nome => "Santa Amélia")
e.cidades.create(:nome => "Santa Cecília do Pavão")
e.cidades.create(:nome => "Santa Cruz de Monte Castelo")
e.cidades.create(:nome => "Santa Fé")
e.cidades.create(:nome => "Santa Helena")
e.cidades.create(:nome => "Santa Inês")
e.cidades.create(:nome => "Santa Isabel do Ivaí")
e.cidades.create(:nome => "Santa Izabel do Oeste")
e.cidades.create(:nome => "Santa Lúcia")
e.cidades.create(:nome => "Santa Maria do Oeste")
e.cidades.create(:nome => "Santa Mariana")
e.cidades.create(:nome => "Santa Mônica")
e.cidades.create(:nome => "Santa Tereza do Oeste")
e.cidades.create(:nome => "Santa Terezinha de Itaipu")
e.cidades.create(:nome => "Santana do Itararé")
e.cidades.create(:nome => "Santo Antônio da Platina")
e.cidades.create(:nome => "Santo Antônio do Caiuá")
e.cidades.create(:nome => "Santo Antônio do Paraíso")
e.cidades.create(:nome => "Santo Antônio do Sudoeste")
e.cidades.create(:nome => "Santo Inácio")
e.cidades.create(:nome => "Sapopema")
e.cidades.create(:nome => "Sarandi")
e.cidades.create(:nome => "Saudade do Iguaçu")
e.cidades.create(:nome => "Sengés")
e.cidades.create(:nome => "Serranópolis do Iguaçu")
e.cidades.create(:nome => "Sertaneja")
e.cidades.create(:nome => "Sertanópolis")
e.cidades.create(:nome => "Siqueira Campos")
e.cidades.create(:nome => "Sulina")
e.cidades.create(:nome => "São Carlos do Ivaí")
e.cidades.create(:nome => "São Jerônimo da Serra")
e.cidades.create(:nome => "São Jorge d'Oeste")
e.cidades.create(:nome => "São Jorge do Ivaí")
e.cidades.create(:nome => "São Jorge do Patrocínio")
e.cidades.create(:nome => "São José da Boa Vista")
e.cidades.create(:nome => "São José das Palmeiras")
e.cidades.create(:nome => "São José dos Pinhais")
e.cidades.create(:nome => "São João")
e.cidades.create(:nome => "São João do Caiuá")
e.cidades.create(:nome => "São João do Ivaí")
e.cidades.create(:nome => "São João do Triunfo")
e.cidades.create(:nome => "São Manoel do Paraná")
e.cidades.create(:nome => "São Mateus do Sul")
e.cidades.create(:nome => "São Miguel do Iguaçu")
e.cidades.create(:nome => "São Pedro do Iguaçu")
e.cidades.create(:nome => "São Pedro do Ivaí")
e.cidades.create(:nome => "São Pedro do Paraná")
e.cidades.create(:nome => "São Sebastião da Amoreira")
e.cidades.create(:nome => "São Tomé")
e.cidades.create(:nome => "Tamarana")
e.cidades.create(:nome => "Tamboara")
e.cidades.create(:nome => "Tapejara")
e.cidades.create(:nome => "Tapira")
e.cidades.create(:nome => "Teixeira Soares")
e.cidades.create(:nome => "Telêmaco Borba")
e.cidades.create(:nome => "Terra Boa")
e.cidades.create(:nome => "Terra Rica")
e.cidades.create(:nome => "Terra Roxa")
e.cidades.create(:nome => "Tibagi")
e.cidades.create(:nome => "Tijucas do Sul")
e.cidades.create(:nome => "Toledo")
e.cidades.create(:nome => "Tomazina")
e.cidades.create(:nome => "Três Barras do Paraná")
e.cidades.create(:nome => "Tunas do Paraná")
e.cidades.create(:nome => "Tuneiras do Oeste")
e.cidades.create(:nome => "Tupãssi")
e.cidades.create(:nome => "Turvo")
e.cidades.create(:nome => "Ubiratã")
e.cidades.create(:nome => "Umuarama")
e.cidades.create(:nome => "Uniflor")
e.cidades.create(:nome => "União da Vitória")
e.cidades.create(:nome => "Uraí")
e.cidades.create(:nome => "Ventania")
e.cidades.create(:nome => "Vera Cruz do Oeste")
e.cidades.create(:nome => "Verê")
e.cidades.create(:nome => "Virmond")
e.cidades.create(:nome => "Vitorino")
e.cidades.create(:nome => "Wenceslau Braz")
e.cidades.create(:nome => "Xambrê")
e.capital = Cidade.find_by_nome_and_estado_id('Curitiba', Estado.find_by_nome('Paraná').id)
e.save

toledo = Cidade.find_by_nome('Toledo')


# Cargos dos Representantes de Turmas
  ['Líder', 'Vice-Líder'].each do |cargo|
    CargoRepresentanteDeTurma.find_or_create_by(descricao: cargo)
  end

# Cargos dos Funcionários do Colégio
  ['Diretor(a)', 'Secretário(a)', 'Professor(a)'].each do |cargo|
    CargoFuncionario.find_or_create_by(descricao: cargo)
  end

# Cargos dos Membros das Chapas ... (Também são da Diretoria do Grêmio)
  ['Presidente', 'Vice-Presidente', 'Primeiro-Secretário(a)', 'Segundo-Secretário(a)', 'Primeiro Tesoureiro(a)', 'Segundo Tesoureiro(a)', 'Orador(a)', 'Diretor(a) Social', 'Diretor(a) de Esportes', 'Diretor(a) Cultural'].each do |cargo|
    CargoMembroChapa.find_or_create_by(descricao: cargo)
  end

# Cargos dos Membros do Conselho Fiscal
  ['Primeiro Efetivo(a)', 'Segundo Efetivo(a)', 'Terceiro Efetivo(a)', 'Primeiro Suplente', 'Segundo Suplente', 'Terceiro Suplente'].each do |cargo|
    CargoMembroConselhoFiscal.find_or_create_by(descricao: cargo)
  end

# Colégio Ayrton Senna da Silva
  c = Colegio.find_or_create_by({nome: 'Ayrton Senna da Silva', cnpj: '11.222.333/0001-11', nome_completo: 'Colégio Estadual Ayrton Senna da Silva', email: 'ceasssf@gmail.com', endereco: 'Rua Carlos Sbaraini, 1789', cep: '85.911-200', telefone: '(45) 3277-9427', fax: '(45) 3277-9427', bairro: 'Jardim São Francisco', cidade_id: toledo.id})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '2ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '3ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '4ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '5ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '6ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '7ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '8ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '9ª', turno: 'Matutino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Matutino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '2ª', turno: 'Matutino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '3ª', turno: 'Matutino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '2ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '3ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '4ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '5ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '6ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '7ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '8ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '9ª', turno: 'Vespertino', ensino: 'Fundamental'})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Vespertino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '2ª', turno: 'Vespertino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '3ª', turno: 'Vespertino', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '1ª', turno: 'Noturno', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '2ª', turno: 'Noturno', ensino: 'Médio'})
  c.turmas.find_or_create_by({serie: '3ª', turno: 'Noturno', ensino: 'Médio'})
  
  c.funcionarios.find_or_create_by({nome: 'José da Silva', telefone: '(11) 1111-1111', cpf: '111.111.111-11', email: 'josedasilva@email.teste', cargo_funcionario_id: 1, cidade_id: toledo.id})
  c.funcionarios.find_or_create_by({nome: 'Maria Josefina', telefone: '(22) 2222-2222', cpf: '222.222.222-22', email: 'mariajosefina@email.teste', cargo_funcionario_id: 2, cidade_id: toledo.id})
  c.funcionarios.find_or_create_by({nome: 'Ângela Pereira', telefone: '(33) 3333-3333', cpf: '333.333.333-33', email: 'angelapereira@email.teste', cargo_funcionario_id: 3, cidade_id: toledo.id})
  
  c.comissao_pro_gremio = ComissaoProGremio.new
  c.conselho_representantes_de_turma = ConselhoRepresentantesDeTurma.new(ano_vigencia: Time.now.year)
  
  c.save
  
# Usuários (Administradores)
  u = Usuario.create({admin: true, nome: 'Diego Morgenstern', cpf: '085.319.559.55', email: 'diego_gjs@hotmail.com', password: '123123123', password_confirmation: '123123123'})
  #u.save!
  #UsuarioMailer.bem_vindo(u).deliver
  
  #u = Usuario.create({admin: true, ativo: true, nome: 'Jéssica Bueno de Moraes', cpf: '010.515.259-50', email: 'je.bueno.moraes@gmail.com', password: '123123123', password_confirmation: '123123123'})
  #u.save!
  #UsuarioMailer.bem_vindo(u).deliver
  

